### ISSUE TITLE
Can you give me an example how to test it

### ISSUE THREAD

**Issue by caojinmeng** [JihongJu/keras-fcn#3]
Hi, I am new to this. 
I have run  trian.py and preseve the model. But  I do not know how to use this model to detect my own image.
I will appreciate it if you can give me an example that I can run directly.

**Comment by JihongJu** [comment]
Hey, I've just uploaded an `infer.py` script which loads images from `../data/VOC2011/ImageSets/Segmentation/test.txt` one by one and gives prediction.

**Comment by LetsExplore11** [comment]
@caojinmeng 
Hi, I want to run the infer.py, but raise an error like this
 "ValueError: Unknown layer: BilinearUpSampling2D".

Could you please give some suggestion to solve this issue?

**Comment by JihongJu** [comment]
Hi @LetsExplore11, that is because `BilinearUpSampling2D` is a custom layer. You need to pass it as an argument to the `load_model`.

**Comment by LetsExplore11** [comment]
@JihongJu 
You have saved my day. Thank you lots.
