### ISSUE TITLE
how fit other model with voc-generator?

### ISSUE THREAD

**Issue by jeansely** [JihongJu/keras-fcn#9]
Hi,
i want to use your files (train.py & voc-generator.py) in my model , but fcn model has num-output=21
that is number of classes , while my model output is a conv2d filter=1 . where should be change for train my model? 

also for run your code in python 3 and windows os should be change these  lines:
in train.py
csv_logger = CSVLogger(
    'output\{}_fcn_vgg16.csv'.format(datetime.datetime.now().strftime("%Y%m%d-%H%M%S")))

in voc_generator.py
self.filenames = np.loadtxt(image_set, dtype=bytes, delimiter="\n").astype(str)

**Comment by JihongJu** [comment]
@jeansely As I mentioned in JihongJu/keras-fcn#8, any files in the `/voc2011` directory are just toy examples to test the FCN model. It is not aimed at running on every OS. Please feel free to fork and modify it for your own use cases.

TO answer your first question, I don't think anything needs to change to fit a model, except the model itself. Maybe you could have a look at the kera documentation how it works.
